# Configuration file for codecov reporting code coverage

# Percentage drop allowed
coverage:
  status:
    project:
      default:
        threshold: 1%

# Disable codecov comments in every PR
comment: off

# From https://docs.codecov.com/docs/notifications#preventing-notifications-until-after-n-builds
# Prevent notifications before completing the more stable workflows (6 CPU and 2 GPU NVIDIA)
# Prevent notifications after merging PRs that run CPU jobs only.
# CPU (6 jobs) and GPU (2 NVIDIA, 1 AMD, 1 Apple, 1 Intel)
codecov:
  notify:
    after_n_builds: 11

flags:
  cuda:
    carryforward: true
    paths:
      - ext/CUDAExt
  amdgpu:
    carryforward: true
    paths:
      - ext/AMDGPUExt
  oneapi:
    carryforward: true
    paths:
      - ext/oneAPIExt
  metal:
    carryforward: true
    paths:
      - ext/MetalExt
