name: ci-cpu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        jobname: [JACC-serial, JACC-threads]
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Instantiate
        uses: julia-actions/setup-julia@v2
        with:
          show-versioninfo: "true"

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1

      - name: Test Serial
        if: contains(matrix.jobname, '-serial')
        uses: julia-actions/julia-runtest@v1

      - name: Test Threads
        if: contains(matrix.jobname, '-threads')
        run: |
          julia -t 4 --project -e 'using Pkg; Pkg.test(;coverage=true)'

      - name: Process Coverage
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        jobname: [JACC-serial, JACC-threads]

    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Instantiate
        run: |
          brew install julia
          julia --project -e 'using Pkg; Pkg.instantiate();'

      - name: Test Serial
        if: contains(matrix.jobname, '-serial')
        run: julia --project -e 'using Pkg; Pkg.test(;coverage=true)'

      - name: Test Threads
        if: contains(matrix.jobname, '-threads')
        run: julia -t 3 --project -e 'using Pkg; Pkg.test(;coverage=true)'

      - name: Process Coverage
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
